version: "3.7"
services:
  bookstore:
    image: iamthanh/bookstore
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bookstore-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    restart: always    
    networks:
      - bookstore-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore

networks:
  bookstore-mysql: 