server:
  port: 3000
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  datasource:
    username: root
    password: thanh1102
    url: jdbc:mysql://localhost:3306/bookstore
  flyway:
    enabled: true
    repair: true