server:
  port: 3000
  error:
    include-stacktrace: never
spring:
  data:
    web:
      pageable:
        max-page-size: 20
        default-page-size: 5
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
#    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysqldb:3306/bookstore
  flyway:
    enabled: true
    repair: true
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG